### ISSUE TITLE
Reactor not connecting to HV connector from immersive engineering

### ISSUE THREAD

**Issue by theArhar** [zeroneye/Powah#235]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Forge: 47.2.17
- Powah: 5.0.4
- TNP Limitless 7 0.35.1 pack

#### Issue description:
Game crashes when trying to connect to IE connector

#### Steps to reproduce:
Build any reactor, connect to IE connector

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

> [14:35:37] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraft.ReportedException: Ticking block entity
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.ClassCastException: class owmii.powah.forge.ForgeEnvHandler$8 cannot be cast to class net.minecraftforge.energy.IEnergyStorage (owmii.powah.forge.ForgeEnvHandler$8 is in module powah@5.0.4 of loader 'TRANSFORMER' @39c93af6; net.minecraftforge.energy.IEnergyStorage is in module forge@47.2.17 of loader 'TRANSFORMER' @39c93af6)
> 	at blusunrize.immersiveengineering.common.blocks.metal.EnergyConnectorBlockEntity.tickServer(EnergyConnectorBlockEntity.java:126) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%231083!/:?]
> 	at blusunrize.immersiveengineering.common.blocks.ticking.IEServerTickableBE.lambda$makeTicker$0(IEServerTickableBE.java:23) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%231083!/:?]
> 	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.world.level.Level.redirect$dnp000$redirectTick(Level.java:4540) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
> 	... 5 more

**Comment by PokeMaserJ** [comment]
The mod from this dev never got past 1.16.5 Forge . You probably want this repo https://github.com/Technici4n/Powah/issues
