### ISSUE TITLE
Game crash on right click?

### ISSUE THREAD

**Issue by FuuNoKamiOka** [zeroneye/Powah#24]
I am still trying to figure out how to use the ender cells and after putting one down and going to right click it with an equal one (Just to get into the UI) the game crashed. The following is said in the report.

java.lang.ClassCastException: owmii.powah.block.cable.CableTile cannot be cast to owmii.powah.block.endercell.EnderCellTile
	at owmii.powah.block.endercell.EnderCellBlock.getContainer(EnderCellBlock.java:68) ~[?:0.2.2] {re:classloading}
	at owmii.lib.block.TileBase.createMenu(TileBase.java:197) ~[?:0.0.23] {re:classloading}
	at owmii.lib.block.BlockBase.func_220051_a(BlockBase.java:204) ~[?:0.0.23] {re:classloading}
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?] {re:classloading,xf:fml:forgeendertech:randomTickBlock}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:281) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1321) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.109.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$408/1644987969.call(Unknown Source) [forge-1.14.4-28.1.109.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

**Comment by owmii** [comment]
What version of powah is this?

**Comment by FuuNoKamiOka** [comment]
1.14.4-0.2.2

**Comment by owmii** [comment]
Fixed in v0.2.3. thanks for reporting!.
