### ISSUE TITLE
Power to redstone not switching over

### ISSUE THREAD

**Issue by MattRidge** [zeroneye/Powah#60]
When utilizing a reactor (latest version) of the mod, I click on redstone to turn on redstone recognition for output and it automatically turns off.

**Comment by owmii** [comment]
What version you have?

**Comment by MattRidge** [comment]
Powah-1.15.2-1.1.10 and Minecraft Forge 1.15.2. 

Powah and it's needed mod to run are the only two mods I have running at this time. I always try new mods by themselves first before adding others into the mix.

**Comment by owmii** [comment]
I think you need to upgrade Lollipop to 1.0.12 that's why, i forgot to make it as dependency, my bad.

**Comment by MattRidge** [comment]
Lollipop-1.15.2-1.0.12 Is the version I am using.

**Comment by owmii** [comment]
Oh, ok i will see what's the problem.

**Comment by DinnerBeef** [comment]
yea this will be nice when its fixed

**Comment by jeremiahwinsley** [comment]
You may have found this already, but I get this error on the server console when clicking the redstone button on an Ender Cell: 
```
[Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.IndexOutOfBoundsException: readerIndex(5) + length(8) exceeds writerIndex(9): PooledUnsafeDirectByteBuf(ridx: 5, widx: 9, cap: 9)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[server-1.15.2-extra.jar:?] {}
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:812) ~[server-1.15.2-extra.jar:?] {}
        at net.minecraft.network.PacketBuffer.readLong(PacketBuffer.java:784) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.PacketBuffer.func_179259_c(PacketBuffer.java:139) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at owmii.lib.network.packets.SNextEnergyConfigPacket.decode(SNextEnergyConfigPacket.java:40) ~[?:1.0.12] {re:classloading}
        at owmii.lib.network.packets.SNextEnergyConfigPacket.decode(SNextEnergyConfigPacket.java:15) ~[?:1.0.12] {re:classloading}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:120) ~[?:?] {re:classloading}
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212] {}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:120) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?] {re:classloading}
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212] {}
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
```

**Comment by owmii** [comment]
Please some one test this for me on server before i release it to the public.
[Powah + lollipop.zip](https://github.com/owmii/Powah/files/4370552/Powah.%2B.lollipop.zip)
This should fix the bug.

Thanks in advance!!

**Comment by MattRidge** [comment]
I put the mods on the server, and the client.  The client is saying mismatched mods.

**Comment by owmii** [comment]
You removed old mods?

**Comment by MattRidge** [comment]
> You removed old mods?

Yes, straight into the trash.

**Comment by owmii** [comment]
Can you give me latest logs from client and the server.
BTW, thanks your help i really appreciate it :]

**Comment by MattRidge** [comment]
Here you go.
[Server.zip](https://github.com/owmii/Powah/files/4371084/Server.zip)
[Client.zip](https://github.com/owmii/Powah/files/4371086/Client.zip)

**Comment by owmii** [comment]
Logs says:  both mods are missing from your server, please re-check your server mods folder
Client are fine, both mods are present.
Sorry for the inconvenience :[

**Comment by MattRidge** [comment]
That's the thing. The server files are there. I'll reload them again.

**Comment by owmii** [comment]
Part from server log:
```
Forge Mod Loader detected missing registry entries.

There are 245 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:item:
    powah:energy_hopper_blazing
    powah:battery_blazing
    powah:dielectric_casing
    powah:ender_cell_starter
    powah:energizing_rod_starter
    powah:ender_cell_hardened
    powah:steel_energized
    powah:energy_cable_spirited.......
```

**Comment by MattRidge** [comment]
![Server mods](https://user-images.githubusercontent.com/13275219/77349228-13a9fb00-6d11-11ea-9a6f-dde96a599b6e.png)

I had to restart the server/computer.... In any case it looks like it's working. Redstone is staying on.

**Comment by MattRidge** [comment]
On a side note, I need to ask other questions about the functionality, how do I do that? Direct conversation?

**Comment by owmii** [comment]
Great!, 
This is my discord: https://discord.gg/A8TP9JY
