### ISSUE TITLE
Player Trasmitter crashes clients on join 1.16.1

### ISSUE THREAD

**Issue by InflamedSebi** [zeroneye/Powah#95]
I built a basic player transmitter and put a dimensional binding card in it.
This crashed my client and does so instantly when I join the server.

Forge 1.16.1-32.0.66
Powah 1.16.1-2.0.2

<details>
<summary>Crashlog</summary>

```
Time: 7/19/20 10:26 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.LogicalSidedProvider$$Lambda$2787/131168518.apply(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60) ~[?:?] {re:classloading}
	at owmii.lib.util.Server.get(Server.java:85) ~[?:2.0.1] {re:classloading}
	at owmii.lib.util.Player.get(Player.java:21) ~[?:2.0.1] {re:classloading}
	at owmii.powah.item.BindingCardItem.getPlayer(BindingCardItem.java:89) ~[?:2.0.2] {re:classloading}
	at owmii.powah.block.transmitter.PlayerTransmitterTile.postTick(PlayerTransmitterTile.java:36) ~[?:2.0.2] {re:classloading}
	at owmii.lib.block.AbstractTickableTile.func_73660_a(AbstractTickableTile.java:28) ~[?:2.0.1] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:533) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1456) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:927) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.66.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1087916281.call(Unknown Source) [forge-1.16.1-32.0.66.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.LogicalSidedProvider.lambda$static$3(LogicalSidedProvider.java:33)
	at net.minecraftforge.fml.LogicalSidedProvider$$Lambda$2787/131168518.apply(Unknown Source)
	at net.minecraftforge.fml.LogicalSidedProvider.get(LogicalSidedProvider.java:60)
	at owmii.lib.util.Server.get(Server.java:85)
	at owmii.lib.util.Player.get(Player.java:21)
	at owmii.powah.item.BindingCardItem.getPlayer(BindingCardItem.java:89)
	at owmii.powah.block.transmitter.PlayerTransmitterTile.postTick(PlayerTransmitterTile.java:36)
	at owmii.lib.block.AbstractTickableTile.func_73660_a(AbstractTickableTile.java:28)

-- Block entity being ticked --
Details:
	Name: powah:player_transmitter // owmii.powah.block.transmitter.PlayerTransmitterTile
	Block: Block{powah:player_transmitter_starter}[top=false]
	Block location: World: (589,64,779), Chunk: (at 13,4,11 in 36,48; contains blocks 576,0,768 to 591,255,783), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Block: Block{powah:player_transmitter_starter}[top=false]
	Block location: World: (589,64,779), Chunk: (at 13,4,11 in 36,48; contains blocks 576,0,768 to 591,255,783), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:533)
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:174)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Inflamedsebi'/30393, l='ClientLevel', x=591.65, y=63.00, z=779.70]]
	Chunk stats: Client Chunk Cache: 729, 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,66,64), Chunk: (at 0,4,0 in 3,4; contains blocks 48,0,64 to 63,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11839679 game time, 12259917 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:445)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:597)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1087916281.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

```

**Comment by InflamedSebi** [comment]
nvm saw this is fixed in the latest version. ty
